LMS_Lexicon2015/Models/Activity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;



namespace LMS_Lexicon2015.Models
{
    public class Activity
    {
        public int Id { get; set; }

        [Display(Name = "Namn")]
        [StringLength(100, ErrorMessage = "{0} måste vara minst {2} tecken och max 100 tecken långt.", MinimumLength = 2)]
        public string Name { get; set; }

        [Required]
        [StringLength(3000, ErrorMessage = "{0} måste vara minst {2} tecken och max 1000 tecken långt.", MinimumLength = 3)]
        [Display(Name = "Beskrivning")]
        public string Description { get; set; }

        [Display(Name = "Startdatum")]
        public DateTime StartDate { get; set; }

        [Display(Name = "Slutdatum")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Kursid")]
        [ForeignKey("CourseOccasion")]
        public int CourseId { get; set; }

        public virtual CourseOccasion CourseOccasion { get; set; } 
    }
}

LMS_Lexicon2015/Models/ActivityType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace LMS_Lexicon2015.Models
{
    public class ActivityType
    {
        [Key]
        public string Name { get; set; }
    }
}

LMS_Lexicon2015/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LMS_Lexicon2015.Models;

namespace LMS_Lexicon2015.Controllers
{
    [Authorize]
    public class ActivitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Activities
        public ActionResult Index()
        {

            ViewBag.NoActivities = "Inga aktiviteter listas här.";
            return View(db.Activitys.ToList()); //vyn tom gör inget om kvar

        }

        // GET:  Skapar sidan med detalj information av aktivitetera
        public ActionResult Details(int? id, int? id2, int? id3)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activitys.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }



            ViewBag.activitiesId = id;
            ViewBag.courseOccasionId = id2;
            ViewBag.groupId = id3;
            ViewBag.Line1 = "/";
            ViewBag.Line2 = "-";
            ViewBag.Line3 = " Till ";

            return View(activity);
        }

        // GET:  //Skapar sidan i vilken man kan lägga till en aktivitet
        [Authorize(Roles = "Lärare")]
        public ActionResult Create(int? id, int? id2)
        {
            ViewBag.courseOccasionId = id;
            ViewBag.groupId = id2;
            ViewBag.StartDate = DateTime.Now;
            ViewBag.EndDate = DateTime.Now;

            //ge startdatum defold värde med klockslag
            DateTime StartDate = DateTime.Now;
            TimeSpan tStartDate = new TimeSpan(09, 00, 0);
            StartDate = StartDate.Date + tStartDate;

            //ge slutdatum defold värde med klockslag
            DateTime EndDate = DateTime.Now;
            TimeSpan tEndDate = new TimeSpan(17, 00, 0);
            EndDate = EndDate.Date + tEndDate;



            ViewBag.StartDate = StartDate;
            ViewBag.EndDate = EndDate;

                ViewBag.Name = new SelectList(db.ActivityTypes, "Name", "Name");//en bäg för rullningslistan på formuläret 

             return View();
        }

        // POST: //Skapar aktiviteten som blev skapad  ovan
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Lärare")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,StartDate,EndDate,CourseId")] Activity activity)
        {
            
            
            if (ModelState.IsValid)
            {
                DateTime CoursesStartDate = db.CourseOccasions.Where(c => c.Id == activity.CourseId).FirstOrDefault().StartDate;
                DateTime CoursesEndDate = db.CourseOccasions.Where(c => c.Id == activity.CourseId).FirstOrDefault().EndDate;


                if (activity.StartDate < CoursesStartDate)
                {
                    //AddErrors(ModelState);
                    ViewBag.courseOccasionId = activity.CourseId;
                    ViewBag.groupId = (int)TempData["GroupId"];
                    ViewBag.StartDate = activity.StartDate;
                    ViewBag.EndDate = activity.EndDate;
                    ViewBag.Name = new SelectList(db.ActivityTypes, "Name", "Name");//en bäg för rullningslistan på formuläret 
                    ModelState.AddModelError("", "Du har angivit ett startdatumet före kursens startdatumet");
                    return View(activity);
                }

                else if (activity.EndDate > CoursesEndDate.AddDays(1))
                {
                    //AddErrors(ModelState);
                    ViewBag.courseOccasionId = activity.CourseId;
                    ViewBag.groupId = (int)TempData["GroupId"];
                    ViewBag.StartDate = activity.StartDate;
                    ViewBag.EndDate = activity.EndDate;
                    ViewBag.Name = new SelectList(db.ActivityTypes, "Name", "Name");//en bäg för rullningslistan på formuläret 
                    ModelState.AddModelError("", "Du har angivit ett slutdatum efter kursens slutdatum" + CoursesEndDate);
                    return View(activity);
                }
                else if (activity.StartDate > activity.EndDate)
                {
                    //AddErrors(ModelState);
                    ViewBag.courseOccasionId = activity.CourseId;
                    ViewBag.groupId = (int)TempData["GroupId"];
                    ViewBag.StartDate = activity.StartDate;
                    ViewBag.EndDate = activity.EndDate;
                    ViewBag.Name = new SelectList(db.ActivityTypes, "Name", "Name");//en bäg för rullningslistan på formuläret 
                    ModelState.AddModelError("", "Du har angivit ett slutdatum före startdatumet ");
                    return View(activity);
                }

                else
                {
                    db.Activitys.Add(activity);
                    db.SaveChanges();
                    return RedirectToAction("Details/" + activity.CourseId + "/" + (int)TempData["GroupId"], "CourseOccasions");
                }
            }

            DateTime StartDate = DateTime.Now;
            TimeSpan tStartDate = new TimeSpan(09, 00, 0);
            StartDate = StartDate.Date + tStartDate;

            DateTime EndDate = DateTime.Now;
            TimeSpan tEndDate = new TimeSpan(17, 00, 0);
            EndDate = EndDate.Date + tEndDate;

            ViewBag.StartDate = StartDate;
            ViewBag.EndDate = EndDate;
            ViewBag.courseOccasionId = activity.CourseId;
            ViewBag.groupId = (int)TempData["GroupId"];
            ViewBag.Name = new SelectList(db.ActivityTypes, "Name", "Name");//en bäg för rullningslistan på formuläret 
            ModelState.AddModelError("", "Du har angivit ett startdatumet och  slutdatumet före kursens startdatumet");
            return View(activity);
        }

        // GET: Skapar sidan på vilken man kan editera aktiviteter
        [Authorize(Roles = "Lärare")]
        public ActionResult Edit(int? id, int? id2, int? id3)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activitys.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }

            ViewBag.activitiesId = id;
            ViewBag.courseOccasionId = id2;
            ViewBag.groupId = id3;
            string selectedId = activity.Name;

            ViewBag.name = new SelectList(db.ActivityTypes, "Name", "Name", selectedId);


            return View(activity);
        }

        // POST: Sparar undan ändringarna ovan
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Lärare")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,StartDate,EndDate,CourseId")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                DateTime CoursesStartDate = db.CourseOccasions.Where(c => c.Id == activity.CourseId).FirstOrDefault().StartDate;
                DateTime CoursesEndDate = db.CourseOccasions.Where(c => c.Id == activity.CourseId).FirstOrDefault().EndDate;

                if (activity.StartDate < CoursesStartDate)
                {
                    //AddErrors(ModelState);
                    ViewBag.courseOccasionId = activity.CourseId;
                    ViewBag.groupId = (int)TempData["GroupId"];
                    ViewBag.StartDate = activity.StartDate;
                    ViewBag.EndDate = activity.EndDate;
                    ViewBag.Name = new SelectList(db.ActivityTypes, "Name", "Name");//en bäg för rullningslistan på formuläret 
                    ModelState.AddModelError("", "Du har angivit ett startdatumet före kursens startdatumet");
                    return View(activity);
                }

                else if (activity.EndDate > CoursesEndDate)
                {
                    //AddErrors(ModelState);
                    ViewBag.courseOccasionId = activity.CourseId;
                    ViewBag.groupId = (int)TempData["GroupId"];
                    ViewBag.StartDate = activity.StartDate;
                    ViewBag.EndDate = activity.EndDate;
                    ViewBag.Name = new SelectList(db.ActivityTypes, "Name", "Name");//en bäg för rullningslistan på formuläret 
                    ModelState.AddModelError("", "Du har angivit ett slutdatum efter kursens slutdatum");
                    return View(activity);
                }
                else if (activity.StartDate > activity.EndDate)
                {
                    //AddErrors(ModelState);
                    ViewBag.courseOccasionId = activity.CourseId;
                    ViewBag.groupId = (int)TempData["GroupId"];
                    ViewBag.StartDate = activity.StartDate;
                    ViewBag.EndDate = activity.EndDate;
                    ViewBag.Name = new SelectList(db.ActivityTypes, "Name", "Name");//en bäg för rullningslistan på formuläret 
                    ModelState.AddModelError("", "Du har angivit ett slutdatum före startdatumet ");
                    return View(activity);
                }

                else
                {
                    db.Entry(activity).State = EntityState.Modified;
                    db.SaveChanges();

LMS_Lexicon2015/Views/Activities/Create.cshtml
@model LMS_Lexicon2015.Models.Activity
<div class="row">
    <div class="col-md-12 extratoppadding">
        @{
            ViewBag.Title = "Create";

            var db = new LMS_Lexicon2015.Models.ApplicationDbContext();
            int CourseId = ViewBag.courseOccasionId;
            var StartDateCourse = db.CourseOccasions.Where(c => c.Id == CourseId).FirstOrDefault().StartDate;
            DateTime valueStartDate = ViewBag.StartDate;
            DateTime valueEndDate = ViewBag.EndDate;
            if (StartDateCourse > DateTime.Today)
            {
                TimeSpan tStartDate = new TimeSpan(09, 00, 0);
                StartDateCourse = StartDateCourse.Date + tStartDate;
                valueStartDate = StartDateCourse;
                TimeSpan tEndDate = new TimeSpan(17, 00, 0);
                var EndDateCource = StartDateCourse.Date + tEndDate;
                valueEndDate = EndDateCource;                          
            }



        }
    </div>
</div>
<div class="row">
    <div class="col-md-12">

        <h2>Skapa ny aktivitet</h2>
        <script src="~/Scripts/Berakna_Datum.js"></script>


        @using (Html.BeginForm(null, null, FormMethod.Post, new { name = "theForm" }))
        {
            @Html.AntiForgeryToken()


            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.Name, "Namn", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Name", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input class="form-control text-box single-line" data-val="true" id="StartDate1" name="StartDate1" type="date" value="@valueStartDate.ToShortDateString()" onchange="calculate()">
                        <input class="form-control text-box single-line" data-val="true" id="StartDate2" name="StartDate2" type="time" value="@valueStartDate.ToShortTimeString()" onchange="calculate()">
                        @Html.HiddenFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input class="form-control text-box single-line" data-val="true" id="EndDate1" name="EndDate1" type="date" value="@valueEndDate.ToShortDateString()" onchange="calculate()">
                        <input class="form-control text-box single-line" data-val="true" id="EndDate2" name="EndDate2" type="time" value="@valueEndDate.ToShortTimeString()" onchange="calculate()">

                        @Html.HiddenFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>



                @*<div class="form-group">
                        @Html.LabelFor(model => model.CourseId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CourseId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="form-group" style="display: none;">
                    @Html.EditorFor(model => model.CourseId, new { htmlAttributes = new { @class = "form-control", @Value = @ViewBag.courseOccasionId } })
                </div>

                @{TempData["GroupId"] = ViewBag.GroupId;}

                <div>
                    <b>Kursens startdatum:</b>
                    @{ 
                        //var db = new LMS_Lexicon2015.Models.ApplicationDbContext();
                     if (ViewBag.courseOccasionId != null)
                     {
                         CourseId = ViewBag.courseOccasionId;
                        @db.CourseOccasions.Where(c => c.Id == CourseId).FirstOrDefault().StartDate.ToShortDateString();
                     }}
                    <b>Kursens slutdatum:</b>
                    @{ if (ViewBag.courseOccasionId != null)
                     {
                         CourseId = ViewBag.courseOccasionId;
                        @db.CourseOccasions.Where(c => c.Id == CourseId).FirstOrDefault().EndDate.ToShortDateString();

                     }}
                </div>
                <br />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Skapa" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div>


            @*@Html.ActionLink("Tillbaka till kursen", "Details/" + (int)ViewBag.GroupId, "Groups")*@

            @Html.ActionLink("Tillbaka till kursen", "Details/" + (int)ViewBag.courseOccasionId + "/" + (int)ViewBag.GroupId, "CourseOccasions")

        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

    </div>
</div>

LMS_Lexicon2015/Views/Activities/Details.cshtml
@model LMS_Lexicon2015.Models.Activity
<div class="row">
    <div class="col-md-12 extratoppadding">
        <h2>Aktivitet detalj</h2>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @*@Html.DisplayNameFor(model => model.StartDate)*@
                Datum
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StartDate.Day)
                @ViewBag.Line1
                @Html.DisplayFor(model => model.StartDate.Month)
                @ViewBag.Line2
                @Html.DisplayFor(model => model.StartDate.Year)
                <span> kl: </span>
                @Html.DisplayFor(model => model.StartDate.Hour)
                <span>:</span>
                @if (Model.StartDate.Minute < 10)
                {
                    <span class="ak">0</span>
                }
                @Html.DisplayFor(model => model.StartDate.Minute)
                @ViewBag.Line3

                @Html.DisplayFor(model => model.EndDate.Day)
                @ViewBag.Line1
                @Html.DisplayFor(model => model.EndDate.Month)
                @ViewBag.Line2
                @Html.DisplayFor(model => model.EndDate.Year)
                <span> kl:  </span>
                @Html.DisplayFor(model => model.EndDate.Hour)
                 <span>:</span>
                @if (Model.EndDate.Minute < 10)
                {
                    <span class="ak">0</span>
                }
                @Html.DisplayFor(model => model.EndDate.Minute)

            </dd>


        </dl>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <p>
            @*@{TempData["GroupId"] = ViewBag.GroupId;}*@
            @*@Html.ActionLink("Ändra", "Edit/" + (int)ViewBag.courseOccasionId + "/" + (int)ViewBag.groupId, "Activities") |*@

            @if (User.IsInRole("Lärare"))
            {
                @Html.ActionLink("Ändra detaljer", "Edit/" + (int)ViewBag.activitiesId + "/" + (int)ViewBag.courseOccasionId + "/" + (int)ViewBag.groupId, "Activities")
            }
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @{
            TempData["groupId"] = (int)ViewBag.groupId;
            TempData["CourseOccasionId"] = (int)ViewBag.courseOccasionId;
            TempData["ActivityId"] = Model.Id;
            TempData["view"] = "Activities";
            TempData["AktivitetTyp"] = Model.Name;
            var db = new LMS_Lexicon2015.Models.ApplicationDbContext();
        }


    </div>
</div>
<div class="row">
    <div class="col-md-12">
               @if (User.IsInRole("Lärare"))
        {
            @Html.Partial("../documents/download", db.Documents.Where(o => o.ActivityId == Model.Id).OrderBy(c => c.Timestamp).ToList())
        }

        @if (User.IsInRole("Elev"))
        {
            @Html.Partial("../documents/download",
    db.Documents.Where(d => d.ActivityId == Model.Id
        && d.UserId == db.Users.Where(u => u.Id == d.UserId && u.Roles.FirstOrDefault().RoleId == db.Roles.Where(r => r.Name == "Lärare").FirstOrDefault().Id).FirstOrDefault().Id))
        }
    </div>
</div>
<h4>
    @Html.ActionLink("Tillbaka till kursen", "Details/" + (int)ViewBag.courseOccasionId + "/" + (int)ViewBag.GroupId, "CourseOccasions")
</h4>

@*SPARA VIKTIGT
    @Html.Partial("../documents/download", db.Documents.Where(o => o.ActivityId == Model.Id).OrderBy(c => c.Timestamp).ToList())

        @Html.Partial("../documents/download",
        db.Documents.Where(d => d.ActivityId == Model.Id
            && d.UserId == db.Users.Where(u => u.Id == d.UserId && u.Roles.FirstOrDefault().RoleId == db.Roles.Where(r => r.Name == "Lärare").FirstOrDefault().Id).FirstOrDefault().Id))*@ 

LMS_Lexicon2015/Views/Activities/Edit.cshtml
@model LMS_Lexicon2015.Models.Activity
<div class="row">
    <div class="col-md-12 extratoppadding">
        @{
            ViewBag.Title = "Edit";
    //DateTime valueStartDate = ViewBag.StartDate;
    //DateTime valueEndDate = ViewBag.EndDate;
        }
    </div>
</div>
<script>
    function calculate() {


        StartDate2 = "14:00:00";
        EndDate2 = "14:00:00";

        StartDate1 = document.theForm.StartDate1.value;
        StartDate2 = document.theForm.StartDate2.value;
        total = StartDate1 + " " + StartDate2;
        document.theForm.StartDate.value = total;

        EndDate1 = document.theForm.EndDate1.value;
        EndDate2 = document.theForm.EndDate2.value;
        total2 = EndDate1 + " " + EndDate2;
        document.theForm.EndDate.value = total2;

    }
</script>
<div class="row">
    <div class="col-md-12">
        <h2>Ändra informationen i aktiviteten</h2>

        @using (Html.BeginForm(null, null, FormMethod.Post, new { name = "theForm" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)


                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("name", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", type = "date", @Value = Model.StartDate.ToShortDateString() } })
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input class="form-control text-box single-line" data-val="true" id="StartDate1" name="StartDate1" type="date" value="@Model.StartDate.ToShortDateString()" onchange="calculate()">
                        <input class="form-control text-box single-line" data-val="true" id="StartDate2" name="StartDate2" type="time" value="@Model.StartDate.ToLongTimeString()" onchange="calculate()">
                        @Html.HiddenFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @Value = Model.StartDate.ToString() } })
                    </div>
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>


                @*<div class="form-group">
                        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", type = "date", @Value = Model.EndDate.ToShortDateString() } })
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input class="form-control text-box single-line" data-val="true" id="EndDate1" name="EndDate1" type="date" value="@Model.EndDate.ToShortDateString()" onchange="calculate()">
                        <input class="form-control text-box single-line" data-val="true" id="EndDate2" name="EndDate2" type="time" value="@Model.EndDate.ToLongTimeString()" onchange="calculate()">
                        @Html.HiddenFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @Value = Model.EndDate.ToString() } })
                    </div>
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>

                @Html.HiddenFor(model => model.CourseId)
                @{TempData["GroupId"] = ViewBag.GroupId;}
            </div>
            <div>
                <b>Kursens Startdatum:</b>
                @{ var db = new LMS_Lexicon2015.Models.ApplicationDbContext();
                 if (ViewBag.courseOccasionId != null)
                 {
                     int CourseId = ViewBag.courseOccasionId;
                    @db.CourseOccasions.Where(c => c.Id == CourseId).FirstOrDefault().StartDate.ToShortDateString();
                 }}
                <b>Kursens Slutdatum:</b>
                @{ if (ViewBag.courseOccasionId != null)
                 {
                     int CourseId = ViewBag.courseOccasionId;
                    @db.CourseOccasions.Where(c => c.Id == CourseId).FirstOrDefault().EndDate.ToShortDateString();

                 }
                }
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Spara" class="btn btn-default" />
                </div>
            </div>
        }
        </div></div>

        <div class="row">
            <div class="col-md-12">
                <div>
                   @* @Html.ActionLink("Tillbaka till kursen", "Details/" + (int)ViewBag.courseOccasionId + "/" + (int)ViewBag.GroupId, "CourseOccasions")*@

                    @Html.ActionLink("Tillbaka till aktivitet", "Details/" + (int)ViewBag.activitiesId + "/" + (int)ViewBag.courseOccasionId + "/" + (int)ViewBag.GroupId, "Activities")

                </div>

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>